import { describe, it, expect, beforeEach } from "vitest";
import { createNotification, sendNotification, markAsRead, getUserNotifications, countUnread, getNotification, clearNotifications } from "../src/services/notification-service";
beforeEach(() => { clearNotifications(); });
describe("createNotification", () => { it("creates with pending status", () => { const n = createNotification("u1", { channel: "email", title: "T", body: "B" }); expect(n.status).toBe("pending"); expect(n.id).toMatch(/^notif-/); }); it("generates unique IDs", () => { const a = createNotification("u1", { channel: "push", title: "A", body: "a" }); const b = createNotification("u1", { channel: "push", title: "B", body: "b" }); expect(a.id).not.toBe(b.id); }); });
describe("sendNotification", () => { it("marks as sent", () => { const n = createNotification("u1", { channel: "email", title: "T", body: "B" }); const s = sendNotification(n.id); expect(s?.status).toBe("sent"); }); it("returns null for missing", () => { expect(sendNotification("x")).toBeNull(); }); it("throws if not pending", () => { const n = createNotification("u1", { channel: "email", title: "T", body: "B" }); sendNotification(n.id); expect(() => sendNotification(n.id)).toThrow(); }); });
describe("markAsRead", () => { it("marks as read", () => { const n = createNotification("u1", { channel: "in_app", title: "T", body: "B" }); const r = markAsRead(n.id); expect(r?.status).toBe("read"); }); });
describe("getUserNotifications", () => { it("filters by user", () => { createNotification("u1", { channel: "email", title: "A", body: "a" }); createNotification("u2", { channel: "email", title: "B", body: "b" }); expect(getUserNotifications("u1")).toHaveLength(1); }); it("filters by channel", () => { createNotification("u1", { channel: "email", title: "E", body: "e" }); createNotification("u1", { channel: "push", title: "P", body: "p" }); expect(getUserNotifications("u1", { channel: "email" })).toHaveLength(1); }); it("filters unread", () => { const n = createNotification("u1", { channel: "email", title: "A", body: "a" }); createNotification("u1", { channel: "email", title: "B", body: "b" }); markAsRead(n.id); expect(getUserNotifications("u1", { unreadOnly: true })).toHaveLength(1); }); });
describe("countUnread", () => { it("counts unread", () => { const n = createNotification("u1", { channel: "email", title: "A", body: "a" }); createNotification("u1", { channel: "push", title: "B", body: "b" }); markAsRead(n.id); expect(countUnread("u1")).toBe(1); }); });
describe("getNotification", () => { it("retrieves by id", () => { const c = createNotification("u1", { channel: "email", title: "T", body: "B" }); expect(getNotification(c.id)?.title).toBe("T"); }); });
